CREATE TABLE MEDICINE (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  TITLE CHAR(64) NOT NULL,
  DOZE FLOAT NOT NULL,
  UNITS CHAR(12) NOT NULL, 
  FREQUENCY TEXT NOT NULL
);

INSERT INTO MEDICINE (TITLE, DOZE, UNITS, FREQUENCY) VALUES ('Topiromax', 0.25, 'g', 'daily');
INSERT INTO MEDICINE (TITLE, DOZE, UNITS, FREQUENCY) VALUES ('Erbisol', 2, 'ml', 'every other day');
INSERT INTO MEDICINE (TITLE, DOZE, UNITS, FREQUENCY) VALUES ('Indometacine', 50, 'mg', 'in necessariness');

UPDATE MEDICINE 
SET DOZE = 0.5, UNITS = 'g' 
WHERE TITLE = 'Indometacine';
UPDATE MEDICINE
SET DOZE = 25, UNITS = 'mg'
WHERE TITLE = 'Topiromax';
DELETE FROM MEDICINE WHERE TITLE = 'Indometacine';
SELECT * FROM MEDICINE
